{% set version = "0.8.15" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-hgnchelper
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/HGNChelper_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/HGNChelper/HGNChelper_{{ version }}.tar.gz
  sha256: 76f8a15bc2d7d70059d0fabdd51e92c917c9a238e7d3ba6cb7ebbb66fd467518

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-splitstackshape
  run:
    - r-base
    - r-splitstackshape

test:
  commands:
    - $R -e "library('HGNChelper')"           # [not win]
    - "\"%R%\" -e \"library('HGNChelper')\""  # [win]

about:
  home: https://github.com/waldronlab/HGNChelper
  license: GPL-2.0-or-later
  summary: Contains functions for identifying and correcting HGNC human gene symbols and MGI mouse gene symbols which have been converted to date format by Excel, withdrawn, or aliased. Also contains functions for reversibly converting between HGNC symbols and valid R names.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: HGNChelper
# Maintainer: Levi Waldron <lwaldron.research@gmail.com>
# Depends: R (>= 3.5.0), methods, utils
# Author: Levi Waldron and Markus Riester
# Version: 0.8.1
# Date: 2019-10-24
# License: GPL (>= 2.0)
# Title: Identify and Correct Invalid HGNC Human Gene Symbols and MGI Mouse Gene Symbols
# Description: Contains functions for identifying and correcting HGNC human gene symbols and MGI mouse gene symbols which have been converted to date format by Excel, withdrawn, or aliased. Also contains functions for reversibly converting between HGNC symbols and valid R names.
# URL: https://github.com/waldronlab/HGNChelper
# BugReports: https://github.com/waldronlab/HGNChelper/issues
# LazyData: TRUE
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# Suggests: testthat, knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-10-24 16:42:15 UTC; lwaldron
# Repository: CRAN
# Date/Publication: 2019-10-24 18:00:03 UTC
